spring:
  application:
    name: api

--- # change port
server:
  port: 8081

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.219.106:3306/atoz
    username: atoz
    password: atoz9897

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # MyBatis

logging:
  level:
    root: info
    com.example.demo: debug  #
    org.apache.ibatis: debug  # MyBatis SQL

---
spring:
  messages:
    basename: messages/messages
    encoding: UTF-8

---
spring:
  web:
    resources:
      static-locations: classpath:/static/

--- # mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

---
file:
  upload-dir: c:/home/atoz/upload/

---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
